### ISSUE TITLE
Hubot adapter?

### ISSUE THREAD

**Issue by arionl** [keybase/keybase-bot#136]
I know this is more of a feature request than an issue but it would be awesome have a hubot adapter for the KeyBase bot (https://hubot.github.com/docs/adapters/). This would make it easy to quickly add bot functions to KeyBase by leveraging a lot of the hubot plugins/scripts. I've looked at a couple of the adapters for other chat systems and they don't seem like a large amount of code. Unfortunately I don't have any JavaScript chops to try to tackle this myself 😞

**Comment by pzduniak** [comment]
I've just released the adapter: https://github.com/keybase/hubot-keybase

Let me know if it's missing some feature!

**Comment by arionl** [comment]
Thank you! I was able to use your adapter to spin up a hubot + keybase in a Docker container. I'm a hubot newbie but I've got the basics working and I'm excited to explore!
