### ISSUE TITLE
AWS Lambda /bin/sh/ command not found

### ISSUE THREAD

**Issue by tyvdh** [keybase/keybase-bot#158]
Trying to deploy to an AWS Lambda via Serverless but getting this error when trying to run the bot.

```
Command failed: which keybase\n/bin/sh: which: command not found\n
```

**Comment by pzduniak** [comment]
You'll probably need to install / compile `which` and then copy that into the bundle. I tend to use Docker for the build process in Serverless.

Alternatively, @malgorithms maybe we should reduce our dependencies on shell stuff and replace (after a code review) this call with https://www.npmjs.com/package/which?

**Comment by maxtaco** [comment]
Thanks for the report, we should definitely fix this

**Comment by tyvdh** [comment]
Wow prompt. Exploring.

**Comment by tyvdh** [comment]
I'll be honest I'm not sure how to 
> install / compile `which` and then copy that into the bundle. Probably above my pay grade for Lambda work.

**Comment by pzduniak** [comment]
I'd have to do some research to actually figure out what's up with `which` in the lambda env. If the issue is anyhow urgent then @zackster published this repo which is just a plain JS func (haven't tested it myself, I just know that he got it to work):
https://github.com/codeforcash/keybase-bot-awslambda

I'll look into making a Serverless template really soon, sounds like a really interesting use case!

**Comment by tyvdh** [comment]
Got the which npm package to work but ultimately it would seem my trial ends with the `Could not find keybase binary` error. Will need help from your end more specifically with Serverless whenever you're able to spare the time.

My branch for the npm which is here: https://github.com/tyvdh/keybase-bot.git

**Comment by zackster** [comment]
Hello Tyler,

If you look at my project you'll notice that I put the keybase binary in ./gopath/bin/keybase and include it in the archive I upload to Lambda.

AWS Lambda doesnt ship with the which binary, or obscures access, so I also modified the keybase-bot node module.

`const keybaseBinaryLocation = await whichKeybase();` became `const keybaseBinaryLocation = process.env['LAMBDA_TASK_ROOT'] + '/gopath/bin/keybase';`

I also modified the keybaseStatus function,

```
if (status && status.Username && status.Device && status.Device.name) {
    return {
      username: status.Username,
      devicename: status.Device.name,
      homeDir
    };
  }
```

became

```
if(status) {
    return {
      username: 'beemo',
      devicename: 'awslambda',
      homeDir
    };
   }
```

**Comment by tyvdh** [comment]
@zackster That's interesting. I'm not very devopy but I may give it a try.

I also wonder if there's a place for https://serverless.com/blog/publish-aws-lambda-layers-serverless-framework/ in all this. Seems like Layers could be utilized here to make this all a bit easier.

**Comment by zackster** [comment]
My solution works directly on AWS Lambda.  I do not see how adding in additional 3rd party vendor would make things easier, but good luck with the journey.  :bow

**Comment by tyvdh** [comment]
Using Layers I was able to get access to the keybase binary executable from @zackster but I get an EACCESS error now from the `copyFile` function.

```
{"errorType":"Error","errorMessage":"spawn /tmp/keybase_bot_2456681e5cfebd541c051cea62a433c4/keybase EACCES","code":"EACCES","stack":["Error: spawn /tmp/keybase_bot_2456681e5cfebd541c051cea62a433c4/keybase EACCES","    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)","    at onErrorNT (internal/child_process.js:415:16)","    at process._tickCallback (internal/process/next_tick.js:63:19)"],"errno":"EACCES","syscall":"spawn /tmp/keybase_bot_2456681e5cfebd541c051cea62a433c4/keybase","path":"/tmp/keybase_bot_2456681e5cfebd541c051cea62a433c4/keybase","spawnargs":["--enable-bot-lite-mode","--log-file","/tmp/keybase_bot_2456681e5cfebd541c051cea62a433c4/logs/keybase.service.log","--home","/tmp/keybase_bot_2456681e5cfebd541c051cea62a433c4","service"]}
```

Seems strange that there is a copy needed of the executable but what do I know.

**Comment by tyvdh** [comment]
Got it! The key was layers and building the binary for Linux 2 for Node 10.x

Once I had the right binary all you have to do is include it as a serverless layer

![Screen Shot 2019-07-13 at 11 48 06 AM](https://user-images.githubusercontent.com/4383610/61173653-1a6a5680-a564-11e9-8606-b529ad84c684.png)

```
layers:
  keybase:
    path: bin
```

and include it in the function

```
functions:
  authSend:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: POST
          cors: true
    layers:
      - { Ref: KeybaseLambdaLayer }
```

Then on the keybase side 

```
private async _prepWorkingDir(): Promise<void> {
  // const keybaseBinaryLocation = await whichKeybase()
  const keybaseBinaryLocation = '/opt/keybase'
  const destination = path.join(this._workingDir, 'keybase')
  await promisify(mkdirp)(this._workingDir)
  await promisify(copyFile)(keybaseBinaryLocation, destination)
}
```

Will need to add toggles for dev vs prod but at least this works in prod!

**Comment by tyvdh** [comment]
Using the Layer method to get `keybase` accessible as an executable I've also now made `which` available as an executable. This allows me to use your code as-is. The critical bit for future reference is [this post](https://serverless.com/blog/publish-aws-lambda-layers-serverless-framework/) and this additional code in the lambda function.

```js
if (process.env.LAMBDA_TASK_ROOT)
    process.env.PATH = `${process.env.PATH}:/opt`
```

**Comment by tyvdh** [comment]
Only downside is the execution time from a dead cold start is around 6 seconds. Loading the Lambda and the two layers takes quite a bit of time. Once it's warm though execution is about 3.5 seconds. For now I'll just increase the timeout of the function that's calling this. In the future though it would be nice to not rely on `which` so I can keep the layer count down and the cold start times as fast as possible.
