### ISSUE TITLE
Chat API Parameter Checking

### ISSUE THREAD

**Issue by thebearjew** [keybase/keybase-bot#16]
When required parameters like `{options: {channel: {...}}` are missing from API methods like `chatSend`, then the library should return a more precise error before invoking the keybase chat api via the service.

**Comment by thebearjew** [comment]
@nathunsmitty thoughts? I do wish that Flow could auto-generate some parameter checking code, but alas.

**Comment by nathunsmitty** [comment]
I support! I suppose an alternative could be passing required options as parameters to the method as opposed to properties in an `options` object. What are your thoughts on that?

Either way, I'm always a fan of nicer error messages!

**Comment by thebearjew** [comment]
Explicit parameters to the api methods would be nicer and easier to check.
Keeping the options object is closer to how the chat api works via the Keybase service on the command line.
Perhaps making this a better library means straying from the CLI api.

**Comment by nathunsmitty** [comment]
My vote is for better library 👍

**Comment by thebearjew** [comment]
This will be handled after #43 lands
