### ISSUE TITLE
Keybase Agent required to be running?

### ISSUE THREAD

**Issue by seigel** [keybase/keybase-bot#166]
I am wondering if it is a hard requirement to have the keybase agent running and authenticated on the server you are executing this code on.  I am imagining that if I wanted to deploy and host the bot on **Heroku** for example, that this would not be possible.

Thanks!

**Comment by pzduniak** [comment]
Keybase is a pretty complicated piece of software so yes, it's a hard requirement. That being said I'm pretty sure it's possible to run binaries in Heroku, it's just somewhat more complicated to set it up.
