### ISSUE TITLE
Suggestions based on user location

### ISSUE THREAD

**Issue by nilsi** [keybase/keybase-bot#216]
Is there any way to write a bot that give suggestions based on a users GPS location?

I would doubt it's possible but better ask here first.

I could let the user go into a website first and post cords to the bot so it can know where the user is but that seems a bit tedious for the user.

**Comment by pzduniak** [comment]
You could send a `/location` from a phone app and then process that message somehow. There's a bunch of types called "location" [here](https://github.com/keybase/keybase-bot/blob/master/src/types/chat1/index.ts).
